idg_user_control:
    resource: "@IDGUserControlBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
user_bundle_routing:
    pattern:  /user/ajax/getUsers
    defaults: { _controller: IDGUserControlBundle:Default:getUsers }
    requirements:
        _method:  POST

new_user_routing:
    pattern:  /user/new/
    defaults: { _controller: IDGUserControlBundle:Default:newUserForm }
