idg_user_control_homepage:
    path:     /
    defaults: { _controller: IDGUserControlBundle:Default:index }

    
user_bundle_routing:
    pattern:  /user/ajax/getUsers
    defaults: { _controller: IDGUserControlBundle:Default:getUsers }


new_user_routing:
    pattern:  /user/new/
    defaults: { _controller: IDGUserControlBundle:Default:newUserForm }
    
new_user_save_routing:
    pattern:  /user/saveNew/
    defaults: { _controller: IDGUserControlBundle:Default:saveNewUser }

get_user_count_routing:
    pattern:  /user/count/
    defaults: { _controller: IDGUserControlBundle:Default:getUserCount }
    
delete_user_routing:
    pattern:  /user/delete/
    defaults: { _controller: IDGUserControlBundle:Default:deleteUser }
    
edit_user_routing:
    pattern:  /user/edit/
    defaults: { _controller: IDGUserControlBundle:Default:editUser }
   
get_lists_routing:
    pattern:  /lists/
    defaults: { _controller: IDGUserControlBundle:Default:getLists }
    
new_lists_routing:
    pattern:  /lists/new/
    defaults: { _controller: IDGUserControlBundle:Default:newListsForm }
    
new_list_save_routing:
    pattern:  /lists/saveNew/
    defaults: { _controller: IDGUserControlBundle:Default:saveNewList }
    
get_lists_count_routing:
    pattern:  /lists/count/
    defaults: { _controller: IDGUserControlBundle:Default:getListsCount }