idg_user_control_homepage:
    path:     /
    defaults: { _controller: IDGUserControlBundle:Default:index }

    
user_bundle_routing:
    pattern:  /user/ajax/getUsers
    defaults: { _controller: IDGUserControlBundle:Default:getUsers }
    options:
        expose: true


new_user_routing:
    pattern:  /user/new/
    defaults: { _controller: IDGUserControlBundle:Default:newUserForm }
    options:
        expose: true
    
new_user_save_routing:
    pattern:  /user/saveNew/
    defaults: { _controller: IDGUserControlBundle:Default:saveNewUser }
    options:
        expose: true

get_user_count_routing:
    pattern:  /user/count/
    defaults: { _controller: IDGUserControlBundle:Default:getUserCount }
    options:
        expose: true
    
delete_user_routing:
    pattern:  /user/delete/
    defaults: { _controller: IDGUserControlBundle:Default:deleteUser }
    options:
        expose: true
    
edit_user_routing:
    pattern:  /user/edit/
    defaults: { _controller: IDGUserControlBundle:Default:editUser }
    options:
        expose: true
   
get_lists_routing:
    pattern:  /lists/
    defaults: { _controller: IDGUserControlBundle:Default:getLists }
    options:
        expose: true
    
new_lists_routing:
    pattern:  /lists/new/
    defaults: { _controller: IDGUserControlBundle:Default:newListsForm }
    options:
        expose: true
    
new_list_save_routing:
    pattern:  /lists/saveNew/
    defaults: { _controller: IDGUserControlBundle:Default:saveNewList }
    options:
        expose: true
    
get_lists_count_routing:
    pattern:  /lists/count/
    defaults: { _controller: IDGUserControlBundle:Default:getListsCount }
    options:
        expose: true
    
delete_list_routing:
    pattern:  /list/delete/
    defaults: { _controller: IDGUserControlBundle:Default:deleteList }
    options:
        expose: true
    
    